[package]
name = "roguelike_common"
version = "0.1.0"
authors = ["Tony Johnson <tony@tosp.net.au>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
specs = "0.16"
specs-derive = "0.4"
